-- CODE 테이블
-- 설명 : 공통코드를 관리한다.
-- 컬럼 
-- 01. SYS_CD / 시스템 코드(대분류) / varchar(20) PK
-- 02. DIV_CD / 분류 코드(소분류) / varchar(20) PK
-- 03. CD / 코드 / varchar(20) PK
-- 04. CD_NM / 코드명 / varchar(45)
-- 05. USE_YN / 사용여부 / varchar(1)
-- 06. CREATE_ID / 생성ID / varchar(45)
-- 07. CREATE_DT / 생성날짜 / date
-- 08. UPDATE_ID / 수정ID / varchar(45)
-- 09. UPDATE_DT / 수정날짜 / date

-- 조회 예시
SELECT * FROM TB_CMM_CODE ORDER BY DIV_CD, SORT_ORDER;


-- 입력 예시
INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'BODY_PART', 'PART_001', '가슴', 'Y', 0, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());

INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'BODY_PART', 'PART_002', '등', 'Y', 1, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());

INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'BODY_PART', 'PART_003', '하체', 'Y', 2, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());

INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'BODY_PART', 'PART_004', '이두', 'Y', 4, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());

INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'BODY_PART', 'PART_005', '삼두', 'Y', 5, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());

INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'BODY_PART', 'PART_006', '어깨', 'Y', 6, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());


-- 저항 운동 코드
INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'RTN_CD', 'STR', '복합근력(프리웨이트)', 'Y', 1, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'RTN_CD', 'ACC', '보조근력(프리웨이트)', 'Y', 2, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'RTN_CD', 'MAC', '보조근력(머신)', 'Y', 3, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_CMM_CODE
(SYS_CD, DIV_CD, CD, CD_NM, USE_YN, SORT_ORDER, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES
('CMM', 'RTN_CD', 'BW', '맨몸저항', 'Y', 4, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());




 -- 삭제 예시
 DELETE FROM TB_CMM_CODE WHERE CD = 'PART_001';
 
 -- 수정 예시
 UPDATE TB_CMM_CODE
    SET CD_NM = '가슴'
  WHERE SYS_CD = 'CMM'
    AND DIV_CD = 'BODY_PART'
    AND CD = 'PART_001';
 
 -- 테이블 초기화
 TRUNCATE TABLE TB_CMM_CODE;