-- RULE 테이블
-- 설명 : 부위-종목 규칙을 관리한다.
-- 컬럼 
-- 01. BODY_PART_CD / 부위코드 / varchar(20) PK
-- 02. RTN_CD / 저항운동 종목 코드 / varchar(20) PK
-- 03. CREATE_ID / 생성ID / varchar(45)
-- 04. CREATE_DT / 생성날짜 / date
-- 05. UPDATE_ID / 수정ID / varchar(45)
-- 06. UPDATE_DT / 수정날짜 / date

-- 조회 예시

SELECT * FROM TB_CMM_RULE;
 COMMIT;
-- 입력 예시
/*
INSERT INTO TB_CMM_RULE(BODY_PART_CD, RTN_CD, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES ('PART_006', 'STR_OHP', 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_CMM_RULE(BODY_PART_CD, RTN_CD, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES ('PART_006', 'STR_PC', 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_CMM_RULE(BODY_PART_CD, RTN_CD, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES ('PART_006', 'STR_PP', 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_CMM_RULE(BODY_PART_CD, RTN_CD, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES ('PART_006', 'ACC_BOR', 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_CMM_RULE(BODY_PART_CD, RTN_CD, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES ('PART_006', 'ACC_SLR', 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_CMM_RULE(BODY_PART_CD, RTN_CD, CREATE_ID, CREATE_DT, UPDATE_ID, UPDATE_DT)
VALUES ('PART_006', 'MAC_SP', 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
*/
