-- TRAINING 테이블
-- 설명 : TRAINING 에 포함되어야 하는 정보를 나열한다.
-- 컬럼 
-- 01. TRAINING_ID / 트레이닝 아이디 / int AI PK
-- 02. TRAINING_NM / 트레이닝 명칭 / varchar(20)
-- 03. TRAINING_DESC / 트레이닝 설명 / varchar(100)
-- 04. TRAINING_CD / 트레이닝 코드 / varchar(20)
-- 05. TRAINING_SET / 트레이닝 세트 / int
-- 06. TRAINING_REPS / 반복횟수 / int
-- 07. TRAINING_WEIGHT / 무게(중량) / int
-- 08. ROUTINE_ID / 루틴 ID / int
-- 09. TRAINING_CREATE_ID / 생성ID / varchar(45)
-- 10. TRAINING_CREATE_DT / 생성날짜 / date
-- 11. TRAINING_UPDATE_ID / 수정ID / varchar(45)
-- 12. TRAINING_UPDATE_DT / 수정날짜 / date

-- 조회 예시
SELECT * FROM TB_RTN_TRAINING;
SELECT * FROM TB_CMM_RULE WHERE BODY_PART_CD = 'PART_003' ORDER BY RTN_CD;
-- STR_SQT STR_DL STR_LNG
-- 입력 예시
INSERT INTO TB_RTN_TRAINING(TRAINING_NM, TRAINING_DESC, TRAINING_CD, TRAINING_SET, TRAINING_REPS, TRAINING_WEIGHT, ROUTINE_ID, TRAINING_CREATE_ID, TRAINING_CREATE_DT, TRAINING_UPDATE_ID, TRAINING_UPDATE_DT)
VALUES('하체 종목', '백스쿼트로한다.', 'STR_SQT', 4, 10, 80, 1, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_RTN_TRAINING(TRAINING_NM, TRAINING_DESC, TRAINING_CD, TRAINING_SET, TRAINING_REPS, TRAINING_WEIGHT, ROUTINE_ID, TRAINING_CREATE_ID, TRAINING_CREATE_DT, TRAINING_UPDATE_ID, TRAINING_UPDATE_DT)
VALUES('하체 종목', '데드리프트로한다.', 'STR_DL', 4, 10, 90, 1, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());
INSERT INTO TB_RTN_TRAINING(TRAINING_NM, TRAINING_DESC, TRAINING_CD, TRAINING_SET, TRAINING_REPS, TRAINING_WEIGHT, ROUTINE_ID, TRAINING_CREATE_ID, TRAINING_CREATE_DT, TRAINING_UPDATE_ID, TRAINING_UPDATE_DT)
VALUES('하체 종목', '런지한다.', 'STR_LNG', 4, 10, 20, 1, 'KIMSANGKI', SYSDATE(), 'KIMSANGKI', SYSDATE());

 -- 삭제 예시
 DELETE FROM TB_RTN_ROUTINE WHERE ROUTINE_ID = 1;
 
 -- 수정 예시
 UPDATE TB_RTN_ROUTINE 
 SET ROUTINE_DESC = '루틴설명'
 WHERE ROUTINE_ID = 1;
 
 -- 테이블 초기화
 TRUNCATE TABLE TB_RTN_ROUTINE;