object Form1: TForm1
  Left = 2213
  Top = 267
  Width = 1334
  Height = 189
  Caption = #51032#47280#49436' [VSPSSZZ014S]'
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object FlatPanel4: TFlatPanel
    Left = 0
    Top = 0
    Width = 1314
    Height = 145
    ParentColor = True
    TabOrder = 0
    UseDockManager = True
    object FlatPanel1: TFlatPanel
      Left = 1
      Top = 1
      Width = 1312
      Height = 54
      ParentColor = True
      TabOrder = 0
      UseDockManager = True
      object FlatLabel2: TFlatLabel
        Left = 9
        Top = 7
        Width = 69
        Alignment = taRightJustify
        TextBorder = 2
        BevelInner = beNone
        BevelOuter = beNone
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        Caption = #49468#53552#44396#48516
        Color = clWhite
        ParentFont = False
        ParentColor = False
        ShowRect = False
        ShowEssential = True
      end
      object FlatLabel1: TFlatLabel
        Left = 177
        Top = 5
        Width = 71
        Alignment = taRightJustify
        TextBorder = 2
        BevelInner = beNone
        BevelOuter = beNone
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        Caption = #51217#49688#51068#51088
        Color = clWhite
        ParentFont = False
        ParentColor = False
        ShowRect = False
        ShowEssential = True
      end
      object Label17: TLabel
        Left = 484
        Top = 4
        Width = 43
        Height = 23
        Alignment = taRightJustify
        AutoSize = False
        Caption = #51217#49688#52376
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentFont = False
        Layout = tlCenter
      end
      object Label18: TLabel
        Left = 475
        Top = 28
        Width = 49
        Height = 23
        Alignment = taRightJustify
        AutoSize = False
        Caption = #51217#49688#44396#48516
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentFont = False
        Layout = tlCenter
      end
      object Label19: TLabel
        Left = 193
        Top = 28
        Width = 49
        Height = 23
        Alignment = taRightJustify
        AutoSize = False
        Caption = #51217#49688#48264#54840
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentFont = False
        Layout = tlCenter
      end
      object Label20: TLabel
        Left = 345
        Top = 4
        Width = 16
        Height = 23
        Alignment = taRightJustify
        AutoSize = False
        Caption = '~'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentFont = False
        Layout = tlCenter
      end
      object Label21: TLabel
        Left = 345
        Top = 28
        Width = 16
        Height = 23
        Alignment = taRightJustify
        AutoSize = False
        Caption = '~'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentFont = False
        Layout = tlCenter
      end
      object Label2: TLabel
        Left = 657
        Top = 7
        Width = 49
        Height = 23
        Alignment = taRightJustify
        AutoSize = False
        Caption = #51221#47148#49692#49436
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentFont = False
        Layout = tlCenter
      end
      object Label5: TLabel
        Left = 652
        Top = 27
        Width = 54
        Height = 23
        Alignment = taRightJustify
        AutoSize = False
        Caption = #51089#50629#49440#53469
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentFont = False
        Layout = tlCenter
      end
      object Label1: TLabel
        Left = 1002
        Top = 5
        Width = 54
        Height = 23
        Alignment = taRightJustify
        AutoSize = False
        Caption = #44144#47000#52376#47749
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentFont = False
        Layout = tlCenter
      end
      object Label3: TLabel
        Left = 25
        Top = 27
        Width = 49
        Height = 23
        Alignment = taRightJustify
        AutoSize = False
        Caption = #52636#47141#50577#49885
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentFont = False
        Layout = tlCenter
      end
      object FlatComboBox1: TFlatComboBox
        Left = 76
        Top = 5
        Width = 100
        Height = 21
        Color = clWindow
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 0
        ItemIndex = -1
      end
      object FlatComboBox2: TFlatComboBox
        Left = 244
        Top = 5
        Width = 100
        Height = 21
        Color = clWindow
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 1
        ItemIndex = -1
      end
      object FlatComboBox4: TFlatComboBox
        Left = 366
        Top = 5
        Width = 100
        Height = 21
        Color = clWindow
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 2
        ItemIndex = -1
      end
      object FlatPanel6: TFlatPanel
        Left = 529
        Top = 5
        Width = 100
        Height = 23
        ParentColor = True
        TabOrder = 3
        UseDockManager = True
        object FlatCheckBox1: TFlatCheckBox
          Left = 5
          Top = 2
          Width = 14
          Height = 17
          TabOrder = 0
          TabStop = True
        end
        object FlatComboBox5: TFlatComboBox
          Left = 20
          Top = 1
          Width = 79
          Height = 21
          Color = clWindow
          ItemHeight = 13
          TabOrder = 1
          ItemIndex = -1
        end
      end
      object FlatPanel16: TFlatPanel
        Left = 529
        Top = 29
        Width = 100
        Height = 23
        ParentColor = True
        TabOrder = 4
        UseDockManager = True
        object FlatCheckBox4: TFlatCheckBox
          Left = 5
          Top = 2
          Width = 14
          Height = 17
          TabOrder = 0
          TabStop = True
        end
        object FlatComboBox7: TFlatComboBox
          Left = 20
          Top = 1
          Width = 79
          Height = 21
          Color = clWindow
          ItemHeight = 13
          TabOrder = 1
          ItemIndex = -1
        end
      end
      object FlatComboBox6: TFlatComboBox
        Left = 244
        Top = 29
        Width = 100
        Height = 21
        Color = clWindow
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 5
        ItemIndex = -1
      end
      object FlatComboBox8: TFlatComboBox
        Left = 366
        Top = 29
        Width = 100
        Height = 21
        Color = clWindow
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 6
        ItemIndex = -1
      end
      object FlatPanel2: TFlatPanel
        Left = 708
        Top = 5
        Width = 285
        Height = 21
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentColor = True
        TabOrder = 7
        UseDockManager = True
        object FlatRadioButton6: TFlatRadioButton
          Left = 6
          Top = 3
          Width = 67
          Height = 17
          Caption = #51217#49688#48264#54840
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #45208#45588#44256#46357
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object FlatRadioButton10: TFlatRadioButton
          Left = 82
          Top = 3
          Width = 47
          Height = 17
          Caption = #49457#47749
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #45208#45588#44256#46357
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
        object FlatRadioButton11: TFlatRadioButton
          Left = 146
          Top = 3
          Width = 47
          Height = 17
          Caption = #48512#49436
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #45208#45588#44256#46357
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object FlatRadioButton12: TFlatRadioButton
          Left = 212
          Top = 3
          Width = 47
          Height = 17
          Caption = #49324#48264
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #45208#45588#44256#46357
          Font.Style = []
          ParentFont = False
          TabOrder = 3
        end
      end
      object FlatPanel3: TFlatPanel
        Left = 708
        Top = 27
        Width = 285
        Height = 23
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ParentColor = True
        TabOrder = 8
        UseDockManager = True
        object FlatRadioButton2: TFlatRadioButton
          Left = 6
          Top = 3
          Width = 67
          Height = 17
          Caption = #44144#47000#52376#48324
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #45208#45588#44256#46357
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object FlatRadioButton1: TFlatRadioButton
          Left = 96
          Top = 3
          Width = 80
          Height = 17
          Caption = #51217#49688#51068#48324
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #45208#45588#44256#46357
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
        object FlatRadioButton3: TFlatRadioButton
          Left = 179
          Top = 3
          Width = 79
          Height = 17
          Caption = #51217#49688#48264#54840#48324
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #45208#45588#44256#46357
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
      end
      object FlatEdit1: TFlatEdit
        Left = 1059
        Top = 5
        Width = 70
        Height = 23
        ColorFlat = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ParentFont = False
        TabOrder = 9
      end
      object FlatSpinEditInteger1: TFlatSpinEditInteger
        Left = 1130
        Top = 5
        Width = 67
        Height = 20
        ColorFlat = clWhite
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        MaxValue = 0
        MinValue = 0
        ParentFont = False
        TabOrder = 10
        Value = 2026
      end
      object FlatComboBox9: TFlatComboBox
        Left = 1198
        Top = 5
        Width = 107
        Height = 21
        Color = clWindow
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 11
        ItemIndex = -1
      end
      object FlatComboBox3: TFlatComboBox
        Left = 76
        Top = 29
        Width = 100
        Height = 21
        Color = clWindow
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ItemHeight = 13
        ParentFont = False
        TabOrder = 12
        ItemIndex = -1
      end
    end
    object FlatPanel5: TFlatPanel
      Left = 1
      Top = 55
      Width = 1312
      Height = 33
      ParentColor = True
      TabOrder = 1
      UseDockManager = True
      object FlatComboBox14: TFlatComboBox
        Left = 1235
        Top = 5
        Width = 69
        Height = 23
        Color = clWindow
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        ItemHeight = 15
        ParentFont = False
        TabOrder = 0
        Text = '  Action'
        ItemIndex = -1
      end
    end
  end
  object FlatPanel35: TFlatPanel
    Left = 1228
    Top = 82
    Width = 77
    Height = 47
    ParentColor = True
    TabOrder = 1
    UseDockManager = True
    object FlatButton4: TFlatButton
      Left = 0
      Top = 1
      Width = 77
      Height = 23
      Caption = #48120#47532#48372#44592
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = #45208#45588#44256#46357
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object FlatButton1: TFlatButton
      Left = 0
      Top = 23
      Width = 77
      Height = 23
      Caption = #51064#49604
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = #45208#45588#44256#46357
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
  end
end
